import Img from "../../../src/assets/images/card-pic.png";
import Tanzania from "../../../src/assets/images/Tanzania.png";
import France from "../../../src/assets/images/France.png";
import Kenya from "../../assets/images/Kenya-1.png";
import Medal from "../../assets/images/Medal.png";
import WFP from "../../assets/images/WFP.png";

export const Cards = [
  {
    id: 1,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 2,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 3,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 4,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 5,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 6,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 7,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 8,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 9,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 10,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 11,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 12,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 13,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 14,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 15,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 16,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 17,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
  {
    id: 18,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
  },
];
export const Orgnaization = [
  {
    id: 1,
    Image: WFP,
    Name: "WFP",
    Flg1: Kenya,
    Flg2: Tanzania,
    Flg3: France,
    Flg4: Kenya,
    Flg5: Tanzania,
    Flg6: France,
  },
  {
    id: 2,
    Image: WFP,
    Name: "WFP",
    Flg1: Kenya,
    Flg2: Tanzania,
    Flg3: France,
    Flg4: Kenya,
    Flg5: Tanzania,
    Flg6: France,
  },
  {
    id: 3,
    Image: WFP,
    Name: "WFP",
    Flg1: Kenya,
    Flg2: Tanzania,
    Flg3: France,
    Flg4: Kenya,
    Flg5: Tanzania,
    Flg6: France,
  },
  {
    id: 4,
    Image: WFP,
    Name: "WFP",
    Flg1: Kenya,
    Flg2: Tanzania,
    Flg3: France,
    Flg4: Kenya,
    Flg5: Tanzania,
    Flg6: France,
  },
];
