import Img from "../../../src/assets/images/card-pic.png";
import Tanzania from "../../../src/assets/images/Tanzania.png";
import France from "../../../src/assets/images/France.png";
import Kenya from "../../assets/images/Kenya-1.png";
import Medal from "../../assets/images/Medal.png";
import WFP from "../../assets/images/WFP.png";
import Ball from "../../assets/images/Ball.png";
import Philipa from "../../assets/images/Philipa.png";
import Scott from "../../assets/images/Scott.png";
import Allen from "../../assets/images/Allen.png";
import Hadley from "../../assets/images/Hadley.png";

export const Cards = [
  {
    id: 1,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 2,
    Image: Ball,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Nicholas Ball",
    Company: "WFP",
    Goal: "16",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 3,
    Image: Philipa,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Zynthia Marrow",
    Company: "WFP",
    Goal: "16",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 4,
    Image: Philipa,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Philippa Santiago",
    Company: "WFP",
    Goal: "16",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 5,
    Image: Allen,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Elizabeth Allen",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 6,
    Image: Allen,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Cassian Jenning",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 7,
    Image: Scott,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Scott Holt",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 8,
    Image: Allen,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Philbert Schwartz",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 9,
    Image: Hadley,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Hadley Leonard",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 10,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Marie Stewart",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 11,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Harley Watkins",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 12,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Larry Villa",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 13,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 14,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 15,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 16,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 17,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
  {
    id: 18,
    Image: Img,
    Medal: Medal,
    Flag1: Kenya,
    Flag2: Tanzania,
    Flag3: France,
    Name: "Tonya Noble",
    Company: "UNICEF",
    Goal: "23",
    Country1: "Kenya",
    Country2: "Tanzania",
    Country3: "France",
    Date: "Last  active: 05/07/2022",
    boardPoints: "30",
    actionPoints: "18",
    discussionPoints: "23",
    collaborationPoints: "10",
    totalPoints: "81",
  },
];
export const Orgnaization = [
  {
    id: 1,
    Image: WFP,
    Name: "WFP",
    Flg1: Kenya,
    Flg2: Tanzania,
    Flg3: France,
    Flg4: Kenya,
    Flg5: Tanzania,
    Flg6: France,
  },
  {
    id: 2,
    Image: WFP,
    Name: "WFP",
    Flg1: Kenya,
    Flg2: Tanzania,
    Flg3: France,
    Flg4: Kenya,
    Flg5: Tanzania,
    Flg6: France,
  },
  {
    id: 3,
    Image: WFP,
    Name: "WFP",
    Flg1: Kenya,
    Flg2: Tanzania,
    Flg3: France,
    Flg4: Kenya,
    Flg5: Tanzania,
    Flg6: France,
  },
  {
    id: 4,
    Image: WFP,
    Name: "WFP",
    Flg1: Kenya,
    Flg2: Tanzania,
    Flg3: France,
    Flg4: Kenya,
    Flg5: Tanzania,
    Flg6: France,
  },
];
